function idT = get_idT(filename, dataLines)
%IMPORTFILE Import data from a text file
%  IDT = IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  IDT = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  idT = importfile("/Users/ernesto/github/Dying_Taste_Cell_analysis/Lysosome Analysis/cell_lys_list.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Mar-2024 08:38:59

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Cell", "Type", "Lysosome", "Health", "TasteBud", "Source", "Dataset", "Folder", "Var9"];
opts.SelectedVariableNames = ["Cell", "Type", "Lysosome", "Health", "TasteBud", "Source", "Dataset", "Folder"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Cell", "Type", "Lysosome", "Health", "TasteBud", "Source", "Dataset", "Folder", "Var9"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Cell", "Type", "Lysosome", "Health", "TasteBud", "Source", "Dataset", "Folder", "Var9"], "EmptyFieldRule", "auto");

% Import the data
idT = readtable(filename, opts);

end